apiVersion: v1
kind: Service
metadata:
  name:  aman-rtp-service
  namespace: aman
spec:
  type: NodePort
  selector:
    app: aman-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000